backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "events"
    label: "Event"
    folder: "content/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Judul Event", name: "title", widget: "string" }
      - { label: "Tanggal", name: "date", widget: "datetime" }
      - { label: "Lokasi", name: "location", widget: "string" }
      - { label: "Poster", name: "poster", widget: "image" }
      - { label: "Deskripsi", name: "body", widget: "markdown" }
